#!/usr/bin/env python3
"""Generate the in-repo codebase map, and gate it against staleness.

The map is an artefact of the repository, not of this skill: it is written into
the project, committed, and travels with the branch. Everything inside the
AUTOGEN markers is derived from the tree — there is no hand-typed number to rot.

    gen_codebase_map.py --init     probe the repo and write .ai-coder.conf
    gen_codebase_map.py            (re)generate the map
    gen_codebase_map.py --check    exit non-zero, naming the stale claim

Wire --check into CI or a pre-commit hook. A map nobody gates is a map that lies
a few weeks later.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from profile import CONFIG_NAME, ProfileError, find_root, load  # noqa: E402

BEGIN = "<!-- AUTOGEN:START — generated by gen_codebase_map.py; do not hand-edit -->"
END = "<!-- AUTOGEN:END -->"

SKIP_DIRS = {
    ".git", ".venv", "venv", "node_modules", "__pycache__", ".mypy_cache",
    ".pytest_cache", ".ruff_cache", "dist", "build", ".tox", "_archive",
}


# ------------------------------------------------------------------ probing


def py_files(d: Path) -> list[Path]:
    out = []
    for p in d.rglob("*.py"):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        out.append(p)
    return sorted(out)


def detect_packages(root: Path) -> list[str]:
    """A top-level directory holding Python source, excluding tests and tooling."""
    names = []
    for child in sorted(root.iterdir()):
        if not child.is_dir() or child.name.startswith(".") or child.name in SKIP_DIRS:
            continue
        if child.name in {"tests", "test", "docs", "scripts", "web", "migrations"}:
            continue
        if py_files(child):
            names.append(child.name)
    return names


def detect_first(root: Path, candidates: list[str]) -> str:
    for c in candidates:
        if (root / c).exists():
            return c
    return ""


def loc(p: Path) -> int:
    try:
        return len(p.read_text(encoding="utf-8", errors="replace").splitlines())
    except OSError:
        return 0


# ------------------------------------------------------------------ sections


def section_packages(root: Path, packages: list[str]) -> list[str]:
    rows = ["| Package | Files | Lines |", "|---|---:|---:|"]
    for name in packages:
        d = root / name
        if not d.is_dir():
            rows.append(f"| `{name}` | — | *missing from tree* |")
            continue
        files = py_files(d)
        rows.append(f"| `{name}` | {len(files)} | {sum(loc(f) for f in files)} |")
    return rows


def section_modules(root: Path, packages: list[str]) -> list[str]:
    out = []
    for name in packages:
        d = root / name
        if not d.is_dir():
            continue
        mods = [
            str(p.relative_to(root))
            for p in py_files(d)
            if p.name != "__init__.py"
        ]
        if mods:
            out.append(f"**`{name}/`** — " + " · ".join(f"`{Path(m).name}`" for m in sorted(mods)))
    return out


def section_migrations(root: Path, rel: str) -> list[str]:
    d = root / rel if rel else None
    if not d or not d.is_dir():
        return ["*no migrations directory configured*"]
    revs = sorted(p.name for p in d.glob("*.py") if p.name != "__init__.py")
    revs += sorted(p.name for p in d.glob("*.sql"))
    if not revs:
        return ["*none*"]
    return [f"Count: {len(revs)} · latest on disk: `{revs[-1]}`", "", "```", *revs, "```"]


def section_tools(root: Path, registries: list[str]) -> list[str]:
    """Names registered in the project's tool sources. Pattern-based on purpose:
    the map records what is there, and a wrong-looking entry is a finding."""
    if not registries:
        return ["*no registry source configured*"]
    out = []
    name_re = re.compile(r"""["']([a-z][a-z0-9_]{2,40})["']\s*,""")
    for rel in registries:
        p = root / rel
        if not p.is_file():
            out.append(f"- `{rel}` — **missing**")
            continue
        text = p.read_text(encoding="utf-8", errors="replace")
        names = sorted(set(name_re.findall(text)))
        out.append(f"- `{rel}` — {len(names)} candidate name(s): " + ", ".join(f"`{n}`" for n in names[:40]))
    return out


def section_models(root: Path, packages: list[str]) -> list[str]:
    cls_re = re.compile(r"^class\s+(\w+)\s*\(", re.M)
    found: list[str] = []
    for name in packages:
        d = root / name
        if not d.is_dir():
            continue
        for p in py_files(d):
            if p.name not in {"models.py", "model.py", "schema.py", "tables.py"}:
                continue
            text = p.read_text(encoding="utf-8", errors="replace")
            for cls in cls_re.findall(text):
                found.append(f"`{cls}` ({p.relative_to(root)})")
    return sorted(found) or ["*no models module found*"]


def build_block(prof) -> str:
    root, packages = prof.root, prof.packages
    lines = [
        BEGIN,
        "",
        "## Packages",
        "",
        *section_packages(root, packages),
        "",
        "## Modules",
        "",
        *section_modules(root, packages),
        "",
        "## Migrations",
        "",
        *section_migrations(root, prof.get("migrations")),
        "",
        "## Registered tool names (candidates)",
        "",
        *section_tools(root, prof.list("registry")),
        "",
        "## Model classes",
        "",
        *section_models(root, packages),
        "",
        END,
    ]
    return "\n".join(lines)


# -------------------------------------------------------------------- write


def splice(existing: str, block: str) -> str:
    if BEGIN in existing and END in existing:
        head = existing.split(BEGIN)[0]
        tail = existing.split(END, 1)[1]
        return head + block + tail
    header = existing.rstrip() + "\n\n" if existing.strip() else (
        "# Codebase map\n\n"
        "Generated. Prose above and below the markers is yours; the block between them\n"
        "is rewritten by `gen_codebase_map.py` and must not be hand-edited.\n\n"
    )
    return header + block + "\n"


def do_init(root: Path) -> int:
    cfg = root / CONFIG_NAME
    if cfg.exists():
        print(f"{CONFIG_NAME} already exists — edit it by hand, or delete it to re-probe.")
        return 1
    packages = detect_packages(root)
    if not packages:
        print("Could not find any top-level Python package. Is this the repo root?", file=sys.stderr)
        return 2
    migrations = detect_first(root, [
        "db/migrations/versions", "migrations/versions", "alembic/versions", "db/migrations",
    ])
    guardrail = detect_first(root, [".claude/hooks/guardrail.py", "scripts/guardrail.py"])
    registry = detect_first(root, ["tools/registry.py", "agent/tools/registry.py"])
    body = [
        "# AI-coder project profile. Every project-specific fact the skill needs.",
        "# Repeatable keys: pair, registry, invariant.",
        "",
        f"packages = {' '.join(packages)}",
        "map = docs/codebase-map.md",
        f"migrations = {migrations}",
        f"guardrail = {guardrail}",
        f"registry = {registry}" if registry else "# registry = tools/registry.py",
        "",
        "# Commands. Under ADP these should match the phase block's GATE / GATE_FULL.",
        "gate = ",
        "gate_full = ",
        "",
        "# Surfaces that must stay in step. Format:",
        "#   pair = <producer file> :: <regex> :: <consumer file>",
        "# Every regex match found in the producer must also appear in the consumer.",
        "# pair = agent/orchestrator.py :: (\\w+Event) :: api/chat.py",
        "",
    ]
    cfg.write_text("\n".join(body), encoding="utf-8")
    print(f"wrote {cfg}")
    print(f"  packages : {' '.join(packages)}")
    print(f"  migrations: {migrations or '(none found)'}")
    print(f"  guardrail : {guardrail or '(none found)'}")
    print("\nFill in gate / gate_full / pair by hand — those cannot be probed reliably.")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate and gate the in-repo codebase map.")
    ap.add_argument("--init", action="store_true", help=f"probe the repo and write {CONFIG_NAME}")
    ap.add_argument("--check", action="store_true", help="fail if the committed map is stale")
    ap.add_argument("--root", help="repo root (default: search upward for the profile)")
    args = ap.parse_args()

    try:
        if args.init:
            return do_init(Path(args.root).resolve() if args.root else Path.cwd().resolve())
        prof = load(Path(args.root).resolve() if args.root else find_root(Path.cwd().resolve()))
    except ProfileError as exc:
        print(f"gen_codebase_map: {exc}", file=sys.stderr)
        return 2

    rel = prof.get("map")
    if not rel:
        print(f"gen_codebase_map: {CONFIG_NAME} has no 'map = <path>'", file=sys.stderr)
        return 2
    target = prof.root / rel
    block = build_block(prof)

    if args.check:
        if not target.is_file():
            print(f"STALE: {rel} does not exist — run gen_codebase_map.py", file=sys.stderr)
            return 1
        current = target.read_text(encoding="utf-8")
        if BEGIN not in current or END not in current:
            print(f"STALE: {rel} has no AUTOGEN block — run gen_codebase_map.py", file=sys.stderr)
            return 1
        have = BEGIN + current.split(BEGIN, 1)[1].split(END, 1)[0] + END
        if have.strip() != block.strip():
            print(f"STALE: {rel} no longer matches the tree.", file=sys.stderr)
            for a, b in zip(have.splitlines(), block.splitlines()):
                if a != b:
                    print(f"  committed: {a}\n  actual   : {b}", file=sys.stderr)
                    break
            print("  run: python3 <skill>/scripts/gen_codebase_map.py", file=sys.stderr)
            return 1
        print(f"map is current: {rel}")
        return 0

    target.parent.mkdir(parents=True, exist_ok=True)
    existing = target.read_text(encoding="utf-8") if target.is_file() else ""
    target.write_text(splice(existing, block), encoding="utf-8")
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
