#!/bin/bash
# ============================================================
# ADP Status — derived dashboard, KHÔNG phải source of truth.
# Derive từ: spec ADP blocks + EVIDENCE + git log + KNOWN_ISSUES.
# % complete tính từ gate-passed (DONE có EVIDENCE), không ai gõ tay.
#
# Usage:
#   bash adp-status.sh [--write] [project_root]
#   --write : ghi docs/PROJECT_STATUS.md, GIỮ NGUYÊN section NOTES_HUMAN.
#             Mặc định chỉ in stdout.
#
# Rule: NOTES_HUMAN = scratch space append-only của người; mọi status
# claim trong đó KHÔNG có hiệu lực (status chính thức sống ở spec/gate).
# ============================================================

set -o pipefail

_ADPTD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB="$_ADPTD/../hooks/adp-lib.sh"
[ -f "$LIB" ] || { echo "FATAL: adp-lib.sh not found" >&2; exit 1; }
# shellcheck source=../hooks/adp-lib.sh
source "$LIB"

WRITE=0
START_DIR="$PWD"
for arg in "$@"; do
    case "$arg" in
        --write) WRITE=1 ;;
        *) START_DIR="$arg" ;;
    esac
done

ROOT=$(adp_find_root "$START_DIR") || { echo "FATAL: không tìm thấy ADP:MANIFEST từ $START_DIR." >&2; exit 1; }
SPEC_DIR=$(adp_manifest_get "$ROOT" SPEC_DIR)
SPEC_DIR=${SPEC_DIR:-docs/tasks}
PROJ_NAME=$(basename "$ROOT")
TS=$(date +%Y-%m-%dT%H:%M)

# ---- State hash + drift ----
CUR_HASH=$(adp_state_hash "$ROOT" "$SPEC_DIR")
HASH_LINE="STATE_HASH: ${CUR_HASH}"
HASH_FILE="$ROOT/docs/.adp-state-hash"
if [ -f "$HASH_FILE" ]; then
    LAST_STAMP=$(tail -1 "$HASH_FILE" 2>/dev/null)
    LAST_HASH=$(echo "$LAST_STAMP" | awk '{print $1}')
    if [ "$CUR_HASH" = "$LAST_HASH" ]; then
        HASH_LINE="${HASH_LINE} (khớp stamp cuối: ${LAST_STAMP})"
    else
        HASH_LINE="${HASH_LINE} ⚠️ DRIFT — stamp cuối: ${LAST_STAMP}"
    fi
else
    HASH_LINE="${HASH_LINE} (chưa có stamp — chưa chạy checkpoint nào)"
fi

# ---- Per-spec table ----
TABLE="| Spec | Phases | ✅ Done | 🔄 In-prog | ⛔ Blocked | 🚫 Cancelled | % | Flags |
|---|---|---|---|---|---|---|---|"
TOTAL_ALL=0; DONE_ALL=0
for f in "$ROOT/$SPEC_DIR"/*.md; do
    [ -f "$f" ] || continue
    grep -q 'ADP:PHASE' "$f" 2>/dev/null || continue
    STATS=$(awk '
        /<!-- ADP:PHASE/ { inb=1; st=""; ev=0; total++; next }
        inb && /^STATUS:/  { st=$2 }
        inb && /^EVIDENCE:/ { ev=1 }
        /<!-- \/ADP -->/ {
            if (inb) {
                if (st=="DONE")        { done++; if (!ev) noev++ }
                else if (st=="IN_PROGRESS") inprog++
                else if (st=="BLOCKED")     blocked++
                else if (st=="CANCELLED")   cancelled++
            }
            inb=0
        }
        END { printf "%d %d %d %d %d %d", total+0, done+0, inprog+0, blocked+0, cancelled+0, noev+0 }
    ' "$f" 2>/dev/null)
    read -r T D I B C NOEV <<< "$STATS"
    [ "$T" -eq 0 ] 2>/dev/null && continue
    EFFECTIVE=$((T - C))
    PCT=0
    [ "$EFFECTIVE" -gt 0 ] && PCT=$((100 * D / EFFECTIVE))
    FLAGS="—"
    [ "$NOEV" -gt 0 ] && FLAGS="⚠️ ${NOEV} DONE thiếu EVIDENCE"
    TABLE="${TABLE}
| $(basename "$f" .md) | ${T} | ${D} | ${I} | ${B} | ${C} | ${PCT}% | ${FLAGS} |"
    TOTAL_ALL=$((TOTAL_ALL + EFFECTIVE)); DONE_ALL=$((DONE_ALL + D))
done
PCT_ALL=0
[ "$TOTAL_ALL" -gt 0 ] && PCT_ALL=$((100 * DONE_ALL / TOTAL_ALL))

# ---- Active phase ----
ACTIVE=$(adp_active_block "$ROOT" "$SPEC_DIR" 2>/dev/null) || ACTIVE=""
ACTIVE_LINE="(không có phase IN_PROGRESS)"
if [ -n "$ACTIVE" ]; then
    A_PHASE=$(echo "$ACTIVE" | grep -m1 'ADP:PHASE' | sed 's/.*ADP:PHASE[ ]*//; s/[ ]*-->.*//')
    A_GOAL=$(echo "$ACTIVE" | adp_block_get GOAL)
    A_SPEC=$(basename "$(echo "$ACTIVE" | adp_block_get SPEC_FILE)" .md)
    ACTIVE_LINE="${A_SPEC} · phase ${A_PHASE} — ${A_GOAL}"
fi

# ---- Debt registry ----
DEBT_LINE="(không có docs/memory/KNOWN_ISSUES.md)"
if [ -f "$ROOT/docs/memory/KNOWN_ISSUES.md" ]; then
    DEBT_N=$(grep -c '^- \|^### ' "$ROOT/docs/memory/KNOWN_ISSUES.md" 2>/dev/null || echo 0)
    DEBT_LINE="${DEBT_N} entries trong docs/memory/KNOWN_ISSUES.md"
fi

# ---- Recent checkpoints ----
GIT_LINES="(không phải git repo)"
if (cd "$ROOT" && git rev-parse --is-inside-work-tree >/dev/null 2>&1); then
    GIT_LINES=$(cd "$ROOT" && git log --oneline -6 --grep='^adp/' 2>/dev/null | sed 's/^/- /')
    [ -z "$GIT_LINES" ] && GIT_LINES="(chưa có checkpoint commit adp/*)"
fi

BODY="# PROJECT STATUS — ${PROJ_NAME}

> AUTO-GENERATED by adp-status.sh @ ${TS} — đây là VIEW derive từ spec + git,
> KHÔNG phải source of truth. ĐỪNG sửa tay phía trên NOTES_HUMAN.

**Overall: ${DONE_ALL}/${TOTAL_ALL} phases gate-passed (${PCT_ALL}%)**
${HASH_LINE}

**Đang chạy:** ${ACTIVE_LINE}

${TABLE}

**Open debts:** ${DEBT_LINE}

**Recent checkpoints (git):**
${GIT_LINES}"

NOTES_MARKER="<!-- NOTES_HUMAN — scratch space append-only. Status claim ở đây KHÔNG có hiệu lực; status chính thức sống ở spec/gate doc. Script không bao giờ sửa phần dưới dòng này. -->"

if [ $WRITE -eq 1 ]; then
    OUT_FILE="$ROOT/docs/PROJECT_STATUS.md"
    NOTES=""
    if [ -f "$OUT_FILE" ]; then
        NOTES=$(awk '/<!-- NOTES_HUMAN/{found=1; next} found{print}' "$OUT_FILE")
    fi
    {
        echo "$BODY"
        echo ""
        echo "$NOTES_MARKER"
        [ -n "$NOTES" ] && echo "$NOTES"
    } > "$OUT_FILE"
    echo "Written: $OUT_FILE (NOTES_HUMAN preserved: $([ -n "$NOTES" ] && echo yes || echo empty))"
else
    echo "$BODY"
fi
exit 0
